# Generated by Django 4.2.4 on 2023-09-03 18:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('line1', models.CharField(max_length=30)),
                ('line2', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('andhra_pradesh', 'ANDHRA PRADESH'), ('arunachal_pradesh', 'ARUNACHAL PRADESH'), ('assam', 'ASSAM'), ('bihar', 'BIHAR'), ('chhattisgarh', 'CHHATTISGARH'), ('goa', 'GOA'), ('gujarat', 'GUJARAT'), ('haryana', 'HARYANA'), ('himachal_pradesh', 'HIMACHAL PRADESH'), ('jammu_and_kashmir', 'JAMMU AND KASHMIR'), ('jharkhand', 'JHARKHAND'), ('karnataka', 'KARNATAKA'), ('kerala', 'KERALA'), ('madhya_pradesh', 'MADHYA PRADESH'), ('maharashtra', 'MAHARASHTRA'), ('manipur', 'MANIPUR'), ('meghalaya', 'MEGHALAYA'), ('mizoram', 'MIZORAM'), ('nagaland', 'NAGALAND'), ('odisha', 'ODISHA'), ('punjab', 'PUNJAB'), ('rajasthan', 'RAJASTHAN'), ('sikkim', 'SIKKIM'), ('tamil_nadu', 'TAMIL NADU'), ('telangana', 'TELANGANA'), ('tripura', 'TRIPURA'), ('uttar_pradesh', 'UTTAR PRADESH'), ('uttarakhand', 'UTTARAKHAND'), ('west_bengal', 'WEST BENGAL')], max_length=20)),
                ('pincode', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('line1', models.CharField(max_length=30)),
                ('line2', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('andhra_pradesh', 'ANDHRA PRADESH'), ('arunachal_pradesh', 'ARUNACHAL PRADESH'), ('assam', 'ASSAM'), ('bihar', 'BIHAR'), ('chhattisgarh', 'CHHATTISGARH'), ('goa', 'GOA'), ('gujarat', 'GUJARAT'), ('haryana', 'HARYANA'), ('himachal_pradesh', 'HIMACHAL PRADESH'), ('jammu_and_kashmir', 'JAMMU AND KASHMIR'), ('jharkhand', 'JHARKHAND'), ('karnataka', 'KARNATAKA'), ('kerala', 'KERALA'), ('madhya_pradesh', 'MADHYA PRADESH'), ('maharashtra', 'MAHARASHTRA'), ('manipur', 'MANIPUR'), ('meghalaya', 'MEGHALAYA'), ('mizoram', 'MIZORAM'), ('nagaland', 'NAGALAND'), ('odisha', 'ODISHA'), ('punjab', 'PUNJAB'), ('rajasthan', 'RAJASTHAN'), ('sikkim', 'SIKKIM'), ('tamil_nadu', 'TAMIL NADU'), ('telangana', 'TELANGANA'), ('tripura', 'TRIPURA'), ('uttar_pradesh', 'UTTAR PRADESH'), ('uttarakhand', 'UTTARAKHAND'), ('west_bengal', 'WEST BENGAL')], max_length=20)),
                ('pincode', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('type', models.CharField(choices=[('agri', 'AGRICULTURE LAND'), ('open', 'OPEN PLOT')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], max_length=10)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default=None)),
                ('type', models.CharField(choices=[('cleaning', 'CLEANING')], max_length=20)),
                ('status', models.CharField(choices=[('review', 'REVIEW'), ('in_progress', 'IN_PROGRESS')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
